/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Luxury Color Palette
        'luxe-black': '#0F1419',
        'luxe-dark': '#1A1F26',
        'luxe-grey': '#2D3142',
        'luxe-light': '#F5F3F0',
        'luxe-cream': '#FEFAF6',
        'luxe-gold': '#D4A574',
        'luxe-gold-dark': '#B8860B',
        'luxe-accent': '#8B7355',
        'luxe-white': '#FFFFFF',
        
        // Legacy colors (maintained for compatibility)
        'error-container': '#ffdad6',
        'surface-dim': '#cfdaf1',
        'on-surface': '#1A1F26',
        'on-secondary-fixed-variant': '#5d4201',
        'on-primary-fixed': '#081b3a',
        'primary-container': '#1a2b4b',
        'surface-container-lowest': '#FEFAF6',
        'surface-tint': '#D4A574',
        'secondary-container': '#E8DCC8',
        'surface-variant': '#E8E3DC',
        'on-secondary': '#FEFAF6',
        'on-surface-variant': '#6B7280',
        'inverse-surface': '#263142',
        outline: '#D1CCBF',
        'on-tertiary-fixed': '#191c1d',
        tertiary: '#151819',
        error: '#ba1a1a',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#261900',
        'on-primary-container': '#8293b8',
        'on-tertiary-fixed-variant': '#454748',
        'inverse-on-surface': '#ebf1ff',
        'surface-container': '#F3EFE8',
        'surface-container-high': '#DEE8FF',
        'surface-bright': '#FEFAF6',
        'on-tertiary-container': '#919394',
        'on-primary-fixed-variant': '#364768',
        primary: '#0F1419',
        'tertiary-container': '#292c2d',
        'surface-container-highest': '#D8E3FA',
        'surface-container-low': '#F9F7F5',
        'on-background': '#1A1F26',
        'primary-fixed': '#d8e2ff',
        'tertiary-fixed': '#e1e3e4',
        'on-primary': '#FEFAF6',
        'tertiary-fixed-dim': '#c5c7c8',
        'primary-fixed-dim': '#b6c6ef',
        'outline-variant': '#E8E3DC',
        'on-error': '#ffffff',
        secondary: '#D4A574',
        'inverse-primary': '#b6c6ef',
        'secondary-fixed': '#E8DCC8',
        'secondary-fixed-dim': '#D4A574',
        background: '#FEFAF6',
        'on-secondary-container': '#4A3F35',
        surface: '#FEFAF6',
        whatsapp: '#25D366',
      },
      borderRadius: {
        DEFAULT: '4px',
        sm: '6px',
        lg: '8px',
        xl: '12px',
        '2xl': '16px',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        gutter: '32px',
        'margin-mobile': '20px',
        'stack-sm': '16px',
        'stack-md': '32px',
        'stack-lg': '64px',
        'container-max': '1200px',
        'margin-desktop': '48px',
      },
      fontFamily: {
        serif: ['\'Playfair Display\'', 'serif'],
        sans: ['\'Inter\'', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        caption: ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'display-lg': ['Playfair Display', 'serif'],
        'label-md': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Playfair Display', 'serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '28px', fontWeight: '400', letterSpacing: '0.3px' }],
        caption: ['13px', { lineHeight: '20px', fontWeight: '500', letterSpacing: '0.4px' }],
        'body-lg': ['18px', { lineHeight: '32px', fontWeight: '400', letterSpacing: '0.3px' }],
        'headline-sm': ['28px', { lineHeight: '36px', fontWeight: '600', letterSpacing: '-0.5px' }],
        'headline-md': ['36px', { lineHeight: '44px', letterSpacing: '-0.8px', fontWeight: '600' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-1.2px', fontWeight: '700' }],
        'label-md': ['13px', { lineHeight: '20px', letterSpacing: '0.8px', fontWeight: '600' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.8px', fontWeight: '700' }],
      },
      maxWidth: {
        'container-max': '1200px',
      },
      boxShadow: {
        'luxury-sm': '0 2px 8px rgba(15, 20, 25, 0.08)',
        'luxury-md': '0 8px 24px rgba(15, 20, 25, 0.12)',
        'luxury-lg': '0 16px 40px rgba(15, 20, 25, 0.16)',
        'luxury-xl': '0 24px 64px rgba(15, 20, 25, 0.2)',
      },
    },
  },
  plugins: [],
}
